version: '3.4'
services:
  weaviate:
    image: semitechnologies/weaviate:latest
    ports:
      - "8080:8080"
    environment:
      - PERSISTENCE_ENABLED=true
      - AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED=true
      - QUERY_DEFAULTS_LIMIT=20
      - CLUSTER_HOSTNAME=node1
    volumes:
      - weaviate_data:/var/lib/weaviate
volumes:
  weaviate_data:
